### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by mayu-tateno** [mayu-tateno/give-me-three#1]
## 概要
Rails 7系
Ruby 3.2.2
Next.js 14系(AppRouter使ってみたい)
MySQL5.7(後で8.0に移行してみたい)
Docker環境
で構築する予定。
主な理由は技術的なキャッチアップもあるが、バックエンドはそこまで複雑なSQLなどは必要ない予定なので、RailsのActiveRecordで十分そうであることと構築のスピードがやはり速いことからRails。小説の表示や書く際のUI/UXにこだわりたい為ReactがベースのNext.jsを使用する。

**Comment by mayu-tateno** [comment]
```
% gem list rails -re

*** REMOTE GEMS ***

rails (7.1.3.4)
```

**Comment by mayu-tateno** [comment]
## 開発メモ
- Rails7.1系(?)からデフォルトでrails new時にDockerfileが自動生成されるようになっている(なんかそんな記事読んだことある)


## 
途中で気づく
```
tatenomayu@tatenomayunoMBP give-me-three % git rev-parse --show-toplevel
/Users/tatenomayu/workspace/next_study/give-me-three
```

```
tatenomayu@tatenomayunoMBP backend % git rev-parse --show-toplevel
/Users/tatenomayu/workspace/next_study/give-me-three/backend
```

```
tatenomayu@tatenomayunoMBP frontend % git rev-parse --show-toplevel
/Users/tatenomayu/workspace/next_study/give-me-three
```
(最初にgive-me-threeディレクトリ内にfrontendとbackendディレクトリを作成して.gitignoreを追加して作った)
rails newの時コマンド間違えたので、一旦backendディレクトリごと削除して、backendディレクトリを作り直してもう一回rails newしたのが原因…？いや、rails newの時にGit追跡対象になってる気がする？

```
cd /Users/tatenomayu/workspace/next_study/give-me-three/backend
rm -rf .git
```
で一旦backend以下でのGitの追跡から外して、ルートでコミットし直した。
submoduleとかにはしなくても大丈夫。

**Comment by mayu-tateno** [comment]
## 実装手順
今後の参考にまとめておく。
```
mkdir give-me-three
cd give-me-three
asdf ruby local 3.2.2
mkdir backend frontend
touch docker-compose.yml .gitignore
```
docker-compose.yml
```
services:
  frontend:
    container_name: give-me-three-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn dev -p 4000
    ports:
      - "8000:4000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    container_name: give-me-three-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    container_name: give-me-three-db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: give_me_three_development
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
```
サーバーなどの起動の`command`をdocker-compose.ymlとそれぞれのDockerfileどちらに書くべきか？
=> 好みかも。docker-compose.ymに書く場合は柔軟性があるし、１箇所にまとめられるので見やすいが、コンテナが多いと見づらくなる？Dockerfileだとそれぞれのコンテナの構築プロセスがわかりやすくなりそう。プロダクトの規模感によって変わってきそう。
servicesの上の方で`version: '3.8'`などとバージョンを指定する記事もよく見るが、コンテナ立ち上げ時にobsoliteの警告が出る。なくても動く。この辺はdocker engineやdocker-compose, docker for desctopなどのバージョンが関係してそう。後でまとめる。

.gitignore
```
.tool-versions
.DS_Store
.keep
```
.keepは空のディレクトリがある状態でgit initするとできがち。空ファイルで消すのがめんどくさいので先にignore。

```
cd backend
bundle init
```

Gemfileができるので、railsの部分のコメントアウトを外して以下のようにする。
```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails'

```

```
bundle exec rails _7.1.3.4_ new . --api -d mysql --skip-test
```
※--skip-testはなくても一緒かも？Gemfileを上書きするかに`Y`で回答。

- .gitignoreに.DS_Storeや.keepを追加
- config/database.ymlのdatabase名などの設定をdocker-compose.ymlの設定に合わせて変更する
- Dockerfileを編集する

```
cd ..
cd frontend
asdf local nodejs 20.14.0
touch Dockerfile
npx create-next-app@latest . --ts
```
Node.jsは最新安定版を使ったが、バージョンの依存関係などのために後から変更する可能性有り。

Dockerfile
```
FROM node:20.14.0

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4000

```
